## Table of Contents
- Arithmatics Operators
- Comparison Operators
    - Equality Comparison on Floating-Point Values
- Logical Operators
    - Logical Expressions involving Boolean Operands
    - Evaluation of Non-Boolean Values in Boolean Context
        - Numeric value
        - String
        - Build-In Composite Data Object
        - The None Keyword
- Bitwise Operators
- Identity Operators
- Augmented Assignment Operators
- Conclusion

In [9]:
# unary positive operators
a = -10
b = 9

In [10]:
# unary negative operators
-a

10

In [8]:
c = a + b
c

-1

In [11]:
c = b - a
c

19

In [13]:
a + b

-1

In [15]:
a * b

-90

In [17]:
a / b

-1.1111111111111112

In [19]:
a % b

8

In [21]:
10 % 3

1

In [23]:
a // b

-2

In [25]:
-4 / 3

-1.3333333333333333

In [38]:
# joze sahih
12 // 3

4

In [29]:
5 ** 2

25

In [31]:
25 ** 2

625

In [33]:
35 ** 2

1225

In [39]:
1111 * 1111

1234321

In [41]:
a ^ b

-1

## Comparison Operators

In [43]:
a < b

True

In [45]:
b < a

False

In [47]:
a ** 2 < b

False

In [49]:
(a + 2) < b

True

In [51]:
x = 1.1 + 2.2

In [53]:
y = 3.3

In [55]:
3.3 == 3.3

True

In [57]:
x == y

False

In [60]:
# fasele item ha az tolerance sanjide mishavad.
tolerance = 0.00001
tolerance

1e-05

In [63]:
abs(y - x) < tolerance

True

In [65]:
import numpy as np

## Logical Operators

In [68]:
not x == 5

True

In [70]:
x = 5

In [72]:
y = 6

In [77]:
x == 5 and y != 6 and z == 2

False

In [79]:
x == 5 or y != 6 or z == 2

True

In [81]:
# = --> assignment operator

In [83]:
x == 2

False

In [88]:
x

5

In [89]:
if x == 2:
    print('hello')
else:
    print('not hello')

not hello


In [90]:
# behtar ast in model nevehsta nashavd ta dark code rahat tar bashad.
not (x < 10) and (y > 9) or (x > 3)

True

- The Boolean Values **False**<br>
- boolean har adad gheyr az sefr motlagh False hastand

In [108]:
bool(0)

False

- Any value that is numerically zero **(0,0.0,0.0+0.0j)**

In [98]:
bool(0.0 + 0.0j)

False

- An **empty string**

In [110]:
bool('')

False

- an object of **a built-n composite data type** which is empty (see later section)

In [107]:
False
# 0 0.0 0+0j
bool([])
bool({})
bool(set())

False

- The Special value denoted by the Python keyword **None**

In [111]:
None

In [118]:
x = []
if x == []: 
    print('There are items in my kist')

There are items in my kist


In [119]:
not x

True

In [123]:
name = ""
if not name:
    print('Name is rquired')

Name is rquired


- Boolean(space) is true

In [125]:
bool(' ')

True

In [127]:
import numpy as np

In [129]:
x = np.array([1,2,3])
x

array([1, 2, 3])

## Bitwise Operators
- In numerical type, use (-) for inverse

In [130]:
~x

array([-2, -3, -4])

In [131]:
x = np.array([True,False,True])
x

array([ True, False,  True])

In [133]:
~x

array([False,  True, False])

In [135]:
not (x.all)

False

## Identity Operators

In [179]:
x = -7
y = -7

In [180]:
id(x)

140431574198896

In [181]:
id(y)

140431574198832

In [182]:
id(y) == id(x)

False

In [183]:
x is y

False

- If the number of memory is between ```-5 to 256```, it exists in same cell of memory so ```x is y TRUE, id(x) == id(y)```

In [184]:
x = -5
y = 256

In [185]:
y = x

In [186]:
id(x)

140432584431728

In [187]:
id(y)

140432584431728

In [188]:
id(x) == id(y)

True

In [166]:
x is y

True

In [190]:
x is not y

False

# Augmented Assignment Operators

In [219]:
x /= 4
x = x / 4
x

0.28515625

In [221]:
x += 20
x

20.006611980730668

In [230]:
x = 2
x **= 4
# x = x ** 4
x

16

In [216]:
x -= 2
x

18.25

In [217]:
x /= 4
# x = x / 4
x

4.5625

## Nice to Know

In [232]:
{
    'ali':(x := 10 + 5)
}

{'ali': 15}