In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
a = np.array([23,21,19,24,35,17,18,24,33,27,21,23])
b = np.array([31,28,19,24,32,27,16,41,23,32,29,33])

In [6]:
a.mean()

23.75

In [8]:
b.mean()

27.916666666666668

In [11]:
# az 100 nafar kasani ke daroo khordant 4.16% bishtar khoob shodan
d = b.mean() - a.mean()
d

4.166666666666668

In [13]:
# be andaze len(b) bia add yek nesbat bede
np.ones(len(b))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.append(np.zeros(len(a)),np.ones(len(b)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [18]:
sales = np.array([
    np.append(np.zeros(len(a)),np.ones(len(b))),
    np.append(a,b)
])
sales

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [23., 21., 19., 24., 35., 17., 18., 24., 33., 27., 21., 23., 31.,
        28., 19., 24., 32., 27., 16., 41., 23., 32., 29., 33.]])

In [19]:
# sattr ha ra shuffel mikonim bor mizanim
sales_t = sales.T
sales_t

array([[ 0., 23.],
       [ 0., 21.],
       [ 0., 19.],
       [ 0., 24.],
       [ 0., 35.],
       [ 0., 17.],
       [ 0., 18.],
       [ 0., 24.],
       [ 0., 33.],
       [ 0., 27.],
       [ 0., 21.],
       [ 0., 23.],
       [ 1., 31.],
       [ 1., 28.],
       [ 1., 19.],
       [ 1., 24.],
       [ 1., 32.],
       [ 1., 27.],
       [ 1., 16.],
       [ 1., 41.],
       [ 1., 23.],
       [ 1., 32.],
       [ 1., 29.],
       [ 1., 33.]])

In [20]:
experiment_label = np.random.randint(0,2,len(sales_t))
experiment_label

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0])

In [24]:
experiment_data = np.array ([
    experiment_label,
    sales_t[:,1]
])   
print(experiment_data)

[[ 1.  0.  0.  0.  0.  1.  0.  1.  0.  0.  1.  1.  0.  0.  0.  1.  0.  0.
   0.  0.  0.  0.  1.  0.]
 [23. 21. 19. 24. 35. 17. 18. 24. 33. 27. 21. 23. 31. 28. 19. 24. 32. 27.
  16. 41. 23. 32. 29. 33.]]


In [26]:
# braye inke 'experiment_data_t' bekhahim transpose konim darim
# omid riazi [bayad tedad sefrh b tedad]
experiment_data_t = experiment_data.T
experiment_data_t

array([[ 1., 23.],
       [ 0., 21.],
       [ 0., 19.],
       [ 0., 24.],
       [ 0., 35.],
       [ 1., 17.],
       [ 0., 18.],
       [ 1., 24.],
       [ 0., 33.],
       [ 0., 27.],
       [ 1., 21.],
       [ 1., 23.],
       [ 0., 31.],
       [ 0., 28.],
       [ 0., 19.],
       [ 1., 24.],
       [ 0., 32.],
       [ 0., 27.],
       [ 0., 16.],
       [ 0., 41.],
       [ 0., 23.],
       [ 0., 32.],
       [ 1., 29.],
       [ 0., 33.]])

In [30]:
experiment_data_t[experiment_data_t[:,0] == 1][:,1]

array([23., 17., 24., 21., 23., 24., 29.])

In [33]:
experiment_data_t[experiment_data_t[:,0] == 0][:,0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.empty([10,1])

array([[4.65379939e-310],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000]])

In [41]:
def sh_exp(N):
    experiment_diff_mean = np.empty([N, 1])
    for times in np.arange(N):
        experiment_label = np.random.randint(0,2,len(sales_t))
        experiment_data = np.array([
            experiment_data = np.array([
                experiment_label,
                sales_t[:,1]
            ]).T
            experiment_diff_mean[times] = experiment_data[experiment_data[:,0]]
        ])

SyntaxError: invalid syntax (193650710.py, line 6)

In [47]:
e1 = sh_exp(N)

NameError: name 'N' is not defined

In [43]:
len(e1[e1 >= d])

NameError: name 'e1' is not defined

In [44]:
# har cheghadr tedad azmayesh bishtar bashad adadi ke be dast ayad ghabel etminan tar hast.
# p_value: ehtemal 
# chon zire 5 darsad nashod mitavan goft ke ma be shavahed kafi naresidim
65 / 1000 * 100

6.5

In [49]:
sns.displot(e1, bins=50)

NameError: name 'e1' is not defined